name: README Update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Fetch files"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: "Update"
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          pip3 install -r requirements.txt
          python3 fetcher.py $API_KEY
      - name: "Commit"
        run: |
          git config --global user.email "2137+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -am "README update Automation"
      - name: "Push changes"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
