name: README Update

on:
  schedule:
    - cron: "1/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Update readme files"
        uses: actions/checkout@main
      - name: "Update README.md"
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          pip3 install -r requirements.txt
          python3 fetcher.py $API_KEY
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: commit
        run: |
          git config --global user.email tymszczur@gmail.com
          git config --global user.name "Maksymilian Tym"
          git add .
          git commit -m "README update Automation" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
